version: '3.4'

services:

  google_img:
    container_name: google_img
    restart: always
    image: google_img:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
      - main
networks:
  main:
